spice/Areas/Admin/Controllers/CouponsController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using spice.Data;
using spice.Models;

namespace spice.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class CouponsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public CouponsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Admin/Coupons
        public async Task<IActionResult> Index()
        {
            return View(await _context.Coupons.ToListAsync());
        }

        // GET: Admin/Coupons/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var coupon = await _context.Coupons
                .FirstOrDefaultAsync(m => m.Id == id);
            if (coupon == null)
            {
                return NotFound();
            }

            return View(coupon);
        }

        // GET: Admin/Coupons/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Admin/Coupons/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Coupon coupon)
        {
            if (ModelState.IsValid)
            {
                var files = HttpContext.Request.Form.Files;
                if (files.Count()>0) {
                    var firstfile = files[0].OpenReadStream();
                    var datastream = new MemoryStream();
                    firstfile.CopyTo(datastream);
                    coupon.Picture = datastream.ToArray();
                }
                _context.Add(coupon);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(coupon);
        }

        // GET: Admin/Coupons/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound($"This Id ={id} is Empty");
            }

            var coupon = await _context.Coupons.FindAsync(id);
            if (coupon == null)
            {
                return NotFound();
            }
            return View(coupon);
        }

        // POST: Admin/Coupons/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Coupon coupon)
        {
            if (id != coupon.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var files = HttpContext.Request.Form.Files;
                    if (files.Count() > 0)
                    {
                        var firstfile = files[0].OpenReadStream();
                        var datastream = new MemoryStream();
                        firstfile.CopyTo(datastream);
                        coupon.Picture = datastream.ToArray();
                    }
                    _context.Update(coupon);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CouponExists(coupon.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(coupon);
        }

        // GET: Admin/Coupons/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var coupon = await _context.Coupons
                .FirstOrDefaultAsync(x => x.Id == id);
            if (coupon == null)
            {
                return NotFound();
            }

            return View(coupon);
        }

        // POST: Admin/Coupons/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var coupon = await _context.Coupons.FindAsync(id);
            _context.Coupons.Remove(coupon);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CouponExists(int id)
        {
            return _context.Coupons.Any(e => e.Id == id);
        }
    }
}

spice/Areas/Customer/Controllers/CartsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using spice.Data;
using spice.Models;
using spice.Models.ViewModel;
using spice.Utility;
using Stripe;
//using Stripe; //paymnet
using System;
using System.Linq;
using System.Security.Claims;

namespace spice.Areas.Customer.Controllers
{
    [Area("Customer")]
    [Authorize]
    public class CartsController : Controller
    {
        private readonly ApplicationDbContext db;

        public CartsController(ApplicationDbContext db)
        {
            this.db = db;
        }
        public IActionResult Index()
        {
            OrderDetailsCartVM orderDetailsCartVM = new OrderDetailsCartVM()
            {
                orderHeader = new Models.OrderHeader(),
            };

            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var currentUser = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            var shoppingcart = db.ShoppingCarts.Where(x => x.ApplicationUserId == currentUser.Value).ToList();
            orderDetailsCartVM.orderHeader.OrderTotalAfterDiscount = 0;

            if (shoppingcart != null)
            {
                orderDetailsCartVM.shoppingCartList = shoppingcart;
            }

            foreach (var item in orderDetailsCartVM.shoppingCartList)
            {
                item.menuItem = db.MenuItems.FirstOrDefault(x => x.Id == item.MenuItemId);
                orderDetailsCartVM.orderHeader.OrderTotalAfterDiscount += item.menuItem.Price * item.Count;

                orderDetailsCartVM.orderHeader.OrderTotalAfterDiscount = Math.Round(orderDetailsCartVM.orderHeader.OrderTotalAfterDiscount, 2);


                if (item.menuItem.Description.Length > 100)
                { item.menuItem.Description = item.menuItem.Description.Substring(0, 99); }
            }
            orderDetailsCartVM.orderHeader.OrderTotalOrginal = orderDetailsCartVM.orderHeader.OrderTotalAfterDiscount;

            if (HttpContext.Session.GetString(SD.CouponCode) != null) {
                orderDetailsCartVM.orderHeader.CouponCode = HttpContext.Session.GetString(SD.CouponCode);
                var couponDB = db.Coupons.FirstOrDefault(x => x.Name.ToLower() == orderDetailsCartVM.orderHeader.CouponCode.ToLower());
                                               
                   orderDetailsCartVM.orderHeader.OrderTotalAfterDiscount= SD.Discount(couponDB, orderDetailsCartVM.orderHeader.OrderTotalOrginal);
            }
          
            return View(orderDetailsCartVM);
        }

        
        public IActionResult ApplyCoupon(OrderDetailsCartVM orderDetailsCartVM) {

            if (orderDetailsCartVM.orderHeader.CouponCode == null)
            {
                orderDetailsCartVM.orderHeader.CouponCode = string.Empty;
            }
            HttpContext.Session.SetString(SD.CouponCode,orderDetailsCartVM.orderHeader.CouponCode);

            return RedirectToAction("Index");
        }
        public IActionResult RemoveCoupon(OrderDetailsCartVM orderDetailsCartVM)
        {

           
            if(HttpContext.Session.GetString(SD.CouponCode)!= null)
                HttpContext.Session.SetString(SD.CouponCode, string.Empty);

            return RedirectToAction("Index");
        }

        public IActionResult Plus(int CardId)
        {
            var shoppingCart = db.ShoppingCarts.FirstOrDefault(x => x.Id == CardId);

            shoppingCart.Count += 1;
            db.SaveChanges();
            return RedirectToAction(nameof(Index));
        }
        public IActionResult Minus(int CardId)
        {
            var shoppingCart = db.ShoppingCarts.FirstOrDefault(x => x.Id == CardId);

            if (shoppingCart.Count > 1) {
                shoppingCart.Count -= 1;
                db.SaveChanges();
            }
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Remove(int CardId)
        {
            var shoppingCart = db.ShoppingCarts.FirstOrDefault(x => x.Id == CardId);

            db.ShoppingCarts.Remove(shoppingCart);
            db.SaveChanges();

            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var currentUser = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            int MinusSession = db.ShoppingCarts
                .Where(x => x.ApplicationUserId == currentUser.Value).ToList().Count;
             
            HttpContext.Session.SetInt32("ShoppingCartCount", MinusSession);
            return RedirectToAction(nameof(Index));
        }

        //Summary ..............................................

        public IActionResult Summary()
        {
            OrderDetailsCartVM orderDetailsCartVM = new OrderDetailsCartVM()
            {
                orderHeader = new Models.OrderHeader(),
            };

            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var currentUser = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);

            var UserInfo = db.applicationUsers.Find(currentUser.Value);

            orderDetailsCartVM.orderHeader.PickUpName = UserInfo.Name;
            orderDetailsCartVM.orderHeader.PhoneNumber = UserInfo.PhoneNumber;
            orderDetailsCartVM.orderHeader.PickUpTime = DateTime.Now;
            var shoppingcart = db.ShoppingCarts.Where(x => x.ApplicationUserId == currentUser.Value).ToList();
            
            
            orderDetailsCartVM.orderHeader.OrderTotalAfterDiscount = 0;

            if (shoppingcart != null)
            {
                orderDetailsCartVM.shoppingCartList = shoppingcart;
            }

            foreach (var item in orderDetailsCartVM.shoppingCartList)
            {
                item.menuItem = db.MenuItems.FirstOrDefault(x => x.Id == item.MenuItemId);
                orderDetailsCartVM.orderHeader.OrderTotalAfterDiscount += item.menuItem.Price * item.Count;

                orderDetailsCartVM.orderHeader.OrderTotalAfterDiscount = Math.Round(orderDetailsCartVM.orderHeader.OrderTotalAfterDiscount, 2);              
            }
            orderDetailsCartVM.orderHeader.OrderTotalOrginal = orderDetailsCartVM.orderHeader.OrderTotalAfterDiscount;

            if (HttpContext.Session.GetString(SD.CouponCode) != null)
            {
                orderDetailsCartVM.orderHeader.CouponCode = HttpContext.Session.GetString(SD.CouponCode);
                var couponDB = db.Coupons.FirstOrDefault(x => x.Name.ToLower() == orderDetailsCartVM.orderHeader.CouponCode.ToLower());

                orderDetailsCartVM.orderHeader.OrderTotalAfterDiscount = SD.Discount(couponDB, orderDetailsCartVM.orderHeader.OrderTotalOrginal);
            }

            return View(orderDetailsCartVM);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        [ActionName("Summary")]
        public IActionResult SummaryPost(OrderDetailsCartVM v , string StripeToken) {

            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var currentUser = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);

            v.shoppingCartList = db.ShoppingCarts.Where(x=>x.ApplicationUserId == currentUser.Value).ToList();

            OrderHeader oh = new OrderHeader();
            oh.PaymentStatus = SD.PaymentStatusPending;
            oh.OrderDate = DateTime.Now;
            oh.UserId = currentUser.Value;
            oh.PickUpName = v.orderHeader.PickUpName;
            oh.PhoneNumber = v.orderHeader.PhoneNumber;
            oh.Status = SD.PaymentStatusPending;
            oh.PickUpTime = Convert.ToDateTime(v.orderHeader.PickUpDate.ToShortDateString()
                + " " + v.orderHeader.PickUpTime.ToShortTimeString());
            
            oh.Comments = v.orderHeader.Comments;            
            


            db.OrderHeaders.Add(oh);
            db.SaveChanges();


           


            foreach (var item in v.shoppingCartList)
            {
                item.menuItem = db.MenuItems.FirstOrDefault(x => x.Id == item.MenuItemId);

                OrderDetail orderDetail = new OrderDetail
                {
                    OrderId = oh.Id,
                    MenuItemId = item.MenuItemId,
                    Count = item.Count,
                    Name=item.menuItem.Name,
                    Description = item.menuItem.Description,
                    Price = item.menuItem.Price
                };
                oh.OrderTotalAfterDiscount += item.menuItem.Price * item.Count;
                oh.OrderTotalOrginal = oh.OrderTotalAfterDiscount;

                db.OrderDetails.Add(orderDetail);
            }


            if (HttpContext.Session.GetString(SD.CouponCode) != null)
            {
                oh.CouponCode = HttpContext.Session.GetString(SD.CouponCode);

               var couponDB = db.Coupons.FirstOrDefault(x => x.Name.ToLower() == v.orderHeader.CouponCode.ToLower());

                oh.OrderTotalAfterDiscount = SD.Discount(couponDB, oh.OrderTotalOrginal);               
            }
            else
            {
                oh.OrderTotalAfterDiscount = v.orderHeader.OrderTotalOrginal;
            }

            db.ShoppingCarts.RemoveRange(v.shoppingCartList);
            HttpContext.Session.SetInt32("ShoppingCartCount",0);

            db.SaveChanges();

            //stripe is a namespace related to stripe.net package so we must call it 
            var option = new ChargeCreateOptions { 
            Amount = Convert.ToInt32(oh.OrderTotalAfterDiscount * 100),
            Currency = "usd",
            Description = "Order ID :"  + oh.Id, 
            Source = StripeToken,
            };

            var service = new ChargeService();
            Charge charge = service.Create(option);

            if (charge.BalanceTransactionId == null)
            {
                oh.PaymentStatus = SD.PaymentStatusRejected;
            }
            else
            { 
                oh.TransactionId= charge.BalanceTransactionId;
            }

spice/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor HttpContextAccessor
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - spice</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet"  href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" />
</head>
<body class="">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand"  asp-area="Customer" asp-controller="Home" asp-action="Index">
                   <label class="text-info" style="cursor:pointer"> <p class="fas fa-pepper-hot"> </p> spice  </label></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" style="margin-bottom:15px"
                            asp-controller="Home" asp-action="Index">
                                <i class="fa-solid fa-house"></i>Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" style="margin-bottom:15px" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                         
                        @if (User.IsInRole(spice.Utility.SD.ManagerRoleUser))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Content Management
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" asp-action="Index" asp-controller="Categories" asp-area="Admin">Category</a>
                                    <a class="dropdown-item" asp-action="Index" asp-controller="SubCategories" asp-area="Admin">Sub Category</a>

                                    <a class="dropdown-item" asp-action="Index" asp-controller="MenuItems" asp-area="Admin">Menu Items List</a>
                                    <a class="dropdown-item" asp-action="Index" asp-controller="Coupons" asp-area="Admin">Coupons</a>
                                    <a class="dropdown-item" href="/Admin/Users/Index">Users</a>
                                </div>
                            </li>
                        }

                        @if (HttpContextAccessor.HttpContext.Session.GetInt32("ShoppingCartCount") == null)
                        {
                            <li class="nav-item" style="margin-top:10px">
                                <a href="#" class="text-info" >
                                    <i class="fas fa-shopping-cart"></i> (0) 
                                </a>
                            </li>
                        }
                        else{
                        
                            <li class="nav-item" style="margin-top:10px">
                                <a asp-action="Index" asp-controller="Carts" asp-area="Customer" class="text-info" >
                                    <i class="fas fa-shopping-cart"></i> (@HttpContextAccessor.HttpContext.Session.GetInt32("ShoppingCartCount")) 
                                </a>
                            </li>
                        
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - spice - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

spice/Views/Shared/_operationbtnDeleteEditDetails.cshtml
@model int   
<td class="text-right">
    <a asp-action="Details" asp-route-id="@Model" class="btn btn-success"><i class="fas fa-list alt"></i> Details</a>
    <a asp-action="Edit"  asp-route-id="@Model" class="btn btn-info"><i class="fas fa-pen alt"></i> Edit</a>
    <a asp-action="Delete" asp-route-id="@Model" class="btn btn-danger"> <i class="fas fa-trash alt"></i> Delete</a>
                        
   </td>