spice/Models/SubCategory.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace spice.Models
{
    public class SubCategory
    {
        [Key]
        public int Id { get; set; }

        [Required]
        [Display(Name="SubCategory")]
        public string Name { get; set; }

        [Display(Name = "Category")]
        public int CategoryId { get; set; }
        [ForeignKey(nameof(CategoryId))]
        public Category Category { get; set; }
    }
}

spice/Areas/Admin/Controllers/SubCategoriesController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using spice.Data;
using spice.Models;
using spice.Models.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;

namespace spice.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class SubCategoriesController : Controller
    {
        string yes = string.Empty;
        private readonly ApplicationDbContext db;

        public SubCategoriesController(ApplicationDbContext db)
        {
            this.db = db;
        }

        // GET: SubCategoriesController
        public ActionResult Index()
        {
            return View(db.SubCategories.Include(x=>x.Category).ToList());
        }

        // GET: SubCategoriesController/Details/5
        public ActionResult Details(int id)
        {
            var mhmdibrahem = db.SubCategories.Include(m => m.Category).SingleOrDefault(x=>x.Id==id);
            if (mhmdibrahem == null)
                return NotFound();

            return View(mhmdibrahem);
        }

        // GET: SubCategoriesController/Create
        public ActionResult Create()
        {
            subandcatViewModel model = new subandcatViewModel()
            {
                CategoriesList = db.Categories.ToList(),
                SubCategory = new Models.SubCategory(),
                


            };  
            return View(model);
        }

        // POST: SubCategoriesController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(subandcatViewModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    

                    var sub2 = new SubCategory();

                   var sub = db.SubCategories.FirstOrDefault(x => x.Name == model.SubCategory.Name);
                    if (sub != null)
                    {
                        ViewBag.exist = "error , record is found";
                        subandcatViewModel modelvm = new subandcatViewModel()
                        {
                            CategoriesList = db.Categories.ToList(),
                            SubCategory = model.SubCategory                            
                        };
                        return View(modelvm);
                    }
                    else
                    {
                        sub2.Name = model.SubCategory.Name;
                        sub2.CategoryId = model.SubCategory.CategoryId;
                        db.SubCategories.Add(sub2);
                        db.SaveChanges();

                        return RedirectToAction(nameof(Index));
                    }
                }
                else {
                    subandcatViewModel modelvm = new subandcatViewModel()
                    {
                        CategoriesList = db.Categories.ToList(),
                        SubCategory = model.SubCategory,
                      
                        statusMsg=yes
                    };
                    return View(modelvm);
                }
            }
            catch(Exception ex)
            {
                return View(ex.Message);
            }
        }

        // GET: SubCategoriesController/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            { return NotFound(); }
            
            
            var x = db.SubCategories.Find(id);
            if(x == null)
            { return NotFound(); }

            subandcatViewModel model = new subandcatViewModel()
            {
                CategoriesList = db.Categories.ToList(),
                SubCategory =x
            };
            return View(model);
            
        }

        // POST: SubCategoriesController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, subandcatViewModel model)
        {
            
            
            try
            {
                if (ModelState.IsValid)
                {
                    var subcat = new SubCategory();
                    subcat = model.SubCategory;
                    db.SubCategories.Update(subcat);
                    db.SaveChanges();
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    ModelState.AddModelError("", "Field Required");
                    subandcatViewModel modell = new subandcatViewModel()
                    {
                        CategoriesList = db.Categories.ToList(),
                    };
                    return View(modell);
                }
                  
            }
            catch
            {
                return View();
            }
        }

        // GET: SubCategoriesController/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            { return NotFound(); }


            var x = db.SubCategories.Include(m=>m.Category).SingleOrDefault(m=>m.Id==id);
            if (x == null)
            { return NotFound(); }
            return View(x);
        }

        // POST: SubCategoriesController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(SubCategory subcategory)
        {
          db.SubCategories.Remove(subcategory);
            db.SaveChanges();
            return RedirectToAction(nameof(Index));
        }
        [HttpGet]
        public IActionResult getsubcategories(int id)
        {
            List<SubCategory> sublist = new List<SubCategory>();
            sublist = db.SubCategories.Where(x => x.CategoryId == id).ToList();
            return Json(new SelectList(sublist,"Id", "Name"));
        }
    }
}

spice/Areas/Admin/Views/SubCategories/Create.cshtml
@model spice.Models.ViewModel.subandcatViewModel;
@{
    ViewData["Title"] = "Create";
}

 <h1>Create</h1>

<h4>SubCategory</h4>
<hr />
<div class="row">
    <div class="col-8 border-right">
        <form asp-action="Create" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
             @if(ViewBag.exist != null)
             {
               <p>@ViewBag.exist</p>
             }
             
             
            <div class="form-group">
                <label asp-for="SubCategory.CategoryId" class="control-label"></label>
                <select asp-for="SubCategory.CategoryId" 
                asp-items="@(new SelectList(Model.CategoriesList,"Id","Name"))" id="selectlistcategories" class="form-control">

                </select>
                <span asp-validation-for="SubCategory.CategoryId" class="text-danger"></span>
            </div>
            
            <div class="form-group">
                <label asp-for="SubCategory.Name" class="control-label"></label>
                <input asp-for="SubCategory.Name" class="form-control" />
                <span asp-validation-for="SubCategory.Name" class="text-danger"></span>
            </div>
            <div class="row">
                <div class="form-group">
                    <input type="submit" value="Create" class="btn btn-primary" />
                </div>
                 <div class="form-group">
                      <a asp-action="Index" class=" btn btn-outline-dark" style="margin-left:5px"> Back to List</a>
                 </div>
             </div>
        </form>
       
    </div>
    <div class="col-3 offset-1">
        <p> existing sub categories</p>
         <div id="i">

         </div>
    </div>
</div>
 
@section Scripts{
    <partial name="_ValidationScriptsPartial" />

    <script>
        function updatesubcatlist(){
            var selectcat = document.getElementById("selectlistcategories").value;
            $list = $('#i');
            $.ajax({
            url:'/Admin/SubCategories/getsubcategories/' +selectcat,
            type:'GET',
            dataType:'text',
                success: function(data) {
                    results = JSON.parse(data);
                    $list.html('');
                    $list.append('<ul class="list-group">')
                    for(i in results) {$list.append('<li class="list-group-items">' + results[i].text + '</li>') }
                    $list.append('</ul>');

                }

            
            });         
        }
           $(document).ready(function() {
                updatesubcatlist(); 
            });
            $('#selectlistcategories').on("change", function() {
                updatesubcatlist(); 
            });
    </script>
}

spice/Areas/Admin/Views/SubCategories/Delete.cshtml
@model spice.Models.SubCategory

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>SubCategory</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Category.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Category.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
    </dl>
    
    <form asp-action="Delete" method="post">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

spice/Areas/Admin/Views/SubCategories/Details.cshtml
 @model spice.Models.SubCategory

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>SubCategory</h4>
    <hr />
    <dl class="row">
         <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Category.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Category.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

spice/Areas/Admin/Views/SubCategories/Edit.cshtml
@model spice.Models.ViewModel.subandcatViewModel

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>subandcatViewModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="SubCategory.Id" />
            <input type="hidden" asp-for="SubCategory.CategoryId" />
                <div class="form-group">
                <label asp-for="SubCategory.CategoryId" class="control-label"></label>
                <select asp-for="SubCategory.CategoryId" disabled
                asp-items="@(new SelectList(Model.CategoriesList,"Id","Name"))" id="selectlistcategories" class="form-control">
                </select>
                <span asp-validation-for="SubCategory.CategoryId" class="text-danger"></span>
            </div>
              <div class="form-group">
                <label asp-for="SubCategory.Name" class="control-label"></label>
                <input asp-for="SubCategory.Name" class="form-control" />
                <span asp-validation-for="SubCategory.Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

spice/Areas/Admin/Views/SubCategories/Index.cshtml
@model IEnumerable<SubCategory>


@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<div class="whitebackground border">
     <div class="row">
         <div class="col-6">
             <h2 class="text-info">SubCategory List</h2>
         </div>
         <div class="col-6 text-right">
              <a class="btn btn-primary" asp-action="Create" asp-controller="SubCategories" asp-area="Admin">  
                  <i class='fas fa-plus-circle'></i> Create New </a>              
         </div>
     </div>
     <div>
        @if (!(@Model.Any()))       @*if (@Model.Count() == 0) { }*@
        {
            <span>No SubCategories...</span>
        }
        else
        {
            <table class="table table-hover border">
                <tr class="table-secondary">
                    <th>@Html.DisplayNameFor(x=>x.Name)</th>
                    <th>@Html.DisplayNameFor(x=>x.Category.Name)</th>
                    <th>

                    </th>
                </tr>
                 @foreach (var item in Model)
                 {
                     <tr>
                         <td>
                              @* @item.Name*@ 
                              @Html.DisplayFor(x=>item.Name)
                         </td>
                         <th>
                              @Html.DisplayFor(x=>item.Category.Name)
                         </th>
                      <partial name="_operationbtnDeleteEditDetails" model="@item.Id">
                     </tr>
                       
                 }
            </table>
           
        }
    </div>
 </div>